### ISSUE TITLE
Timestamp not correct (Arduino)

### ISSUE THREAD

**Issue by Ghenghiz** [plotly/arduino-api#22]
Hi, 

I'm using the streaming_ethernet library for arduino to permanently send electricity consumption of my home to the plot.ly server. At the start of the arduino the timestamps are correct. But after a while (5 mins or so) the timestamps of the recorded values ar lying in the future. The difference between the actual time and the timestamp of new points in the plot is getting more and more the longer the recording is. I'm using the code that is given in almost every example. 

void loop() {

      Mlight = analogRead(2);
      Mpower = emon1.calcIrms(1480); // This is taken from openenergymonitor.com

      
      graph.plot(millis(), Mlight, tokens[0]);
      graph.plot(millis(), Mpower, tokens[1]);

    delay(100);      
  }

**Comment by thepatman** [comment]
I have the same issue. I have made a workaround by feeding plotly fake values for millis.

define a variable above your functions.

i.e.
`long int fakeMillis;`

then increment it in your loop "slower" than real Millis() would.
taking your code could be

```
void loop() {

  Mlight = analogRead(2);
  Mpower = emon1.calcIrms(1480); // This is taken from openenergymonitor.com


  graph.plot(fakeMillis, Mlight, tokens[0]);
  graph.plot(fakeMillis, Mpower, tokens[1]);
  if(fakeMillis<100000){
        fakeMillis += 50;
        }
  else{
          fakeMillis = 1;
}

delay(100);      

}
```

I put 50 because you have a delay(100) 

Hope it works for you.

**Comment by paulcounter** [comment]
I am having the same issue. I have tried the tweak you mentioned (or a very similar method) but the inaccuracy is still there. Is plot.ly aware of this problem and, if so, what are your thoughts about it?

**Comment by paulcounter** [comment]
Can we have a response to this issue please. It seems to be an issue with the way that plotly converts millis() to a time stamp. I.e. it is using something other than 1000 per second. Any ideas?

**Comment by thepatman** [comment]
I did mention it on the plot.ly site and I think they are aware but obviously can't resolve it.  my fakeMillis worked for over a month but it was for my grand-daughters school project ad has no been dismantled. Sorry. :-(

**Comment by rabbithat** [comment]
+1
I first asked about this issue 9 months ago, and it remains unresolved.  WTF?

**Comment by TheGiolly** [comment]
Please fix this bug

**Comment by alexander-daniel** [comment]
Hello there, seems like what you're experiencing is some time-drift, as the Arduino does **NOT** have a good Real-Time-Clock. In order to get around this, we tried time-stamping using the `millis()` method. If you're running a long-standing experiment, I suggest you look at an RTC module so that the Arduino can output accurate time. From there, you can replace the call to `millis()` with your own RTC generated time. 
This should give you more accurate readings in the long term.

**Comment by TheGiolly** [comment]
Alexander, i have a big drift. After 1h ok, after 2h ok, but after 3h it start to drift a lot (+1h). I log temperature every hour

**Comment by protozoon** [comment]
Hi! Just got familiar with Plotly+Arduino. I experience "drift" with millis() when stream breaks normally after a minute of nothing to stream and when api reconnects, plotly changes its timestamp to that new time and when mills() from arduinos last boot is added to that, it is naturally off, the amount of disconnected seconds to the future. I'll set up a RTC timestamp.

**Comment by alexander-daniel** [comment]
Great. I suggest using an RTC module if you need accuracy, Unfortunately this is one of the limitations of the Arduino. Alternatively, you can tether it to a raspberry pi and use something like http://johnny-five.io/ to communicate. That way you can use the real time from the raspberry pi, which is much more accurate. 

Closing this issue as we cannot fix Arduino's clock...
